FROM golem-slate
RUN apt-get -qq -y install imagemagick

#docker run --rm -it -v ${PWD}:/golem/work go-le-m /bin/bash -C ./start.sh
#GVM image hash: b02b0be31c29b3b1982de333add8c660deb245cfa036f284a73a35b1